### ISSUE TITLE
Discussion on function naming

### ISSUE THREAD

**Issue by wu-clan** [tiangolo/asyncer#25]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Asyncer documentation, with the integrated search.
- [X] I already searched in Google "How to X in Asyncer" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to Asyncer but to [AnyIO](https://github.com/agronholm/anyio).
- [X] I already checked if it is not related to Asyncer but to [Trio](https://github.com/python-trio/trio).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
import anyio
import asyncer

def sync_work(name: str):
    time.sleep(1)
    return f"Hello, {name}"

async def do_async_work(name: str):
    message = asyncer.run_async(sync_work)(name=name)
    return message

async def main():
    message = await do_async_work(name="World")
    print(message)

asyncer.run(main)
```

### Description

It's strange to name the three main functions, Why not use regular name?
- asyncify
- syncify
- runnify

The first two unified can be understood, but runnify is always weird.

Why not
- run_async
- run_sync
- run

### Operating System

Windows

### asyncer Version

0.0.1

### Python Version

3.X

**Comment by bazylhorsey** [comment]
more on this, I don't really understand in the docs the difference in use between runnify and syncify. At first glance it makes sense, but then when you unravel it in your head runnify is just another way of handling async in a sync context. More info on how they're distinguished would be good.
