### ISSUE TITLE
how do you get mypy working with paramspec... I cannot

### ISSUE THREAD

**Issue by jessekrubin** [tiangolo/asyncer#5]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Asyncer documentation, with the integrated search.
- [X] I already searched in Google "How to X in Asyncer" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to Asyncer but to [AnyIO](https://github.com/agronholm/anyio).
- [X] I already checked if it is not related to Asyncer but to [Trio](https://github.com/python-trio/trio).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
n/a
```

### Description

Hi tiangolo!

Looks like a nice lib. I have a lib called asyncify (https://github.com/dynamic-graphics-inc/dgpy-libs/tree/master/libs/asyncify) `pip install asyncify` that has an asyncify function. I cannot get my asyncify function to work with mypy and paramspec. do you have any suggestions.

### Operating System

Linux, Windows, macOS

### asyncer Version

n/a

### Python Version

36+

### Additional Context

This is a random question and I thought you might be interested. DM me if you are interested in taking over the asyncify name as it is imo a better name.

**Comment by tiangolo** [comment]
Thanks! You need the latest version of **mypy**, `ParamSpec` support is very recent, in `0.930`.

**Comment by jessekrubin** [comment]
@tiangolo thanks. I was using 920 :/
