### ISSUE TITLE
Invalid images path in tutorial directory

### ISSUE THREAD

**Issue by smoeinbbp** [tiangolo/asyncer#8]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Asyncer documentation, with the integrated search.
- [X] I already searched in Google "How to X in Asyncer" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to Asyncer but to [AnyIO](https://github.com/agronholm/anyio).
- [X] I already checked if it is not related to Asyncer but to [Trio](https://github.com/python-trio/trio).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
-
```

### Description

Hi @tiangolo.
Images path in tutorial directory is invalid. It seems all of them need a `/doc` in the beginning of their path.
In #7, I've fixed one of them in `asyncify` section of the tutorial page. Do you think other cases need to be resolved in the same PR?
Thanks for this awesome library. 🥳

### Operating System

Linux

### asyncer Version

-

### Python Version

-

**Comment by tiangolo** [comment]
Thanks for the interest!

As I was mentioning in the PR, you should read the docs on the website https://asyncer.tiangolo.com/ , GitHub is only for the source.

On the docs website you will also see the embedded examples, etc.

**Comment by smoeinbbp** [comment]
Oh, okay.
So I close this issue.
